### Lesson create
POST http://192.168.1.103:8080/api/v1/lesson/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NDI2OTI3MzY2IiwiaWF0IjoxNzYwODE2ODQ0LCJleHAiOjE3NjA5MDMyNDR9.QaHer2T742rJSVBSnzSQ21UHedNx8OA1CLbAvssHcIU

{
  "title": "New lesson",
  "vimeo_url": "https://player.vimeo.com/video/1128506430",
  "pdf_url": "https://admission.usat.uz",
  "section_id": "7d646ed0-acfe-11f0-adb5-43e6001eea00"
}

### Lesson get all
GET http://192.168.1.103:8080/api/v1/lesson/get?sectionId=7d646ed0-acfe-11f0-adb5-43e6001eea00
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NDI2OTI3MzY2IiwiaWF0IjoxNzYwODE2ODQ0LCJleHAiOjE3NjA5MDMyNDR9.QaHer2T742rJSVBSnzSQ21UHedNx8OA1CLbAvssHcIU
