### 1. Make Payment Request
POST http://192.168.1.103:8080/api/v1/payment/make
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NDI2OTI3MzY2IiwiaWF0IjoxNzYxMzI1NTk3LCJleHAiOjE3NjE0MTE5OTd9.ihvImp1K7T1bxWyggf3K88nUSLDd4ZqIsI8uG8J_xyE

{
  "number": "9999999999999999",
  "expire": "9999",
  "course_id": "COURSE123"
}

### 2. Verify Payment Request
POST http://192.168.1.103:8080/api/v1/payment/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NDI2OTI3MzY2IiwiaWF0IjoxNzYxMzI1NTk3LCJleHAiOjE3NjE0MTE5OTd9.ihvImp1K7T1bxWyggf3K88nUSLDd4ZqIsI8uG8J_xyE

{
  "token": "Mashallah",
  "code": "9999",
  "course_id": "COURSE123"
}